"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { apiFetch } from "@/lib/api-client";
import { Download, CheckCircle2, AlertTriangle, ShieldAlert, ArrowRight } from "lucide-react";

export default function ImportAIAssessmentPage() {
  const router = useRouter();
  const [rawText, setRawText] = useState("");
  const [validationResult, setValidationResult] = useState<any>(null);
  const [validating, setValidating] = useState(false);
  const [importing, setImporting] = useState(false);
  const [importSuccess, setImportSuccess] = useState(false);

  const handleValidate = async () => {
    setValidating(true);
    setValidationResult(null);
    setImportSuccess(false);

    try {
      const res = await apiFetch("/ai/validate-assessment", {
        method: "POST",
        body: JSON.stringify({ rawResponse: rawText }),
      });
      setValidationResult(res);
    } catch (err: any) {
      setValidationResult({
        valid: false,
        errors: err.details && err.details.length > 0 
          ? err.details 
          : [err.message || "Failed to validate raw response"],
      });
    } finally {
      setValidating(false);
    }
  };

  const handleImport = async () => {
    if (!validationResult?.valid) return;
    setImporting(true);

    try {
      await apiFetch("/ai/import-assessment", {
        method: "POST",
        body: JSON.stringify({
          rawResponse: rawText,
          parsedPayload: validationResult.parsedPayload,
          promptVersionId: validationResult.promptVersionId,
        }),
      });

      setImportSuccess(true);
      setTimeout(() => {
        router.push("/");
        router.refresh();
      }, 2000);
    } catch (err: any) {
      alert(err.message || "Failed to import assessment");
    } finally {
      setImporting(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="border-b border-slate-800 pb-4">
        <h1 className="text-xl font-bold tracking-tight text-slate-100 flex items-center gap-2">
          <Download className="w-5 h-5 text-sky-400" />
          <span>Import External AI Assessment</span>
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          Paste the raw JSON response generated by your AI model to update capability scores.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Step 1: Raw Response Paste Area */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4">
          <h2 className="text-xs font-semibold text-slate-200 uppercase tracking-wider">
            1. Paste Raw AI Model Output
          </h2>
          <textarea
            rows={16}
            value={rawText}
            onChange={(e) => {
              setRawText(e.target.value);
              setValidationResult(null);
            }}
            placeholder="Paste raw response string or markdown-fenced ```json ... ``` here..."
            className="w-full bg-slate-950 border border-slate-800 rounded-lg p-3 text-xs font-mono text-slate-300 focus:outline-none focus:border-sky-500 leading-relaxed resize-none"
          />

          <button
            type="button"
            disabled={!rawText.trim() || validating}
            onClick={handleValidate}
            className="w-full bg-sky-600 hover:bg-sky-500 text-white font-medium text-xs py-2 px-4 rounded-lg transition-colors shadow-sm disabled:opacity-50 flex items-center justify-center gap-2"
          >
            <span>{validating ? "Validating Payload..." : "Validate Schema & Taxonomy"}</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>

        {/* Step 2: Validation Results & Import Execution */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-4 flex flex-col justify-between">
          <div>
            <h2 className="text-xs font-semibold text-slate-200 uppercase tracking-wider mb-3">
              2. Schema Validation &amp; Preview
            </h2>

            {importSuccess ? (
              <div className="bg-emerald-950/80 border border-emerald-800 text-emerald-300 p-4 rounded-lg text-xs space-y-2">
                <div className="flex items-center gap-2 font-bold text-sm text-emerald-200">
                  <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                  <span>Assessment Successfully Imported!</span>
                </div>
                <p>
                  Scores and provenance updated atomically. Redirecting to dashboard...
                </p>
              </div>
            ) : validationResult ? (
              validationResult.valid ? (
                <div className="space-y-4">
                  <div className="bg-emerald-950/50 border border-emerald-800 text-emerald-300 p-3 rounded-lg text-xs flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                    <span>Payload is valid! Schema &amp; taxonomy match 100%.</span>
                  </div>

                  <div className="bg-slate-950 border border-slate-800 rounded-lg p-3 text-xs space-y-2 max-h-[300px] overflow-y-auto">
                    <div className="font-semibold text-slate-200">Parsed Capabilities ({validationResult.parsedPayload.capabilities.length}):</div>
                    <ul className="space-y-1 text-slate-300">
                      {validationResult.parsedPayload.capabilities.map((c: any, idx: number) => (
                        <li key={idx} className="flex items-center justify-between border-b border-slate-900 pb-1">
                          <span>{c.capability}</span>
                          <span className="font-bold text-sky-400">{c.score}/10</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ) : (
                <div className="bg-red-950/50 border border-red-800 text-red-300 p-4 rounded-lg text-xs space-y-2">
                  <div className="flex items-center gap-2 font-semibold text-red-200">
                    <ShieldAlert className="w-4 h-4 text-red-400 shrink-0" />
                    <span>Validation Failed ({validationResult.errors.length} errors)</span>
                  </div>
                  <ul className="list-disc list-inside space-y-1 text-red-300 font-mono text-[11px]">
                    {validationResult.errors.map((err: string, idx: number) => (
                      <li key={idx}>{err}</li>
                    ))}
                  </ul>
                </div>
              )
            ) : (
              <div className="h-[250px] flex items-center justify-center border border-dashed border-slate-800 rounded-lg text-xs text-slate-500 text-center p-6">
                Paste JSON output on the left and click &quot;Validate Schema &amp; Taxonomy&quot;.
              </div>
            )}
          </div>

          <div>
            <button
              type="button"
              disabled={!validationResult?.valid || importing || importSuccess}
              onClick={handleImport}
              className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-medium text-xs py-2.5 px-4 rounded-lg transition-colors shadow-sm disabled:opacity-50 flex items-center justify-center gap-2"
            >
              <Download className="w-4 h-4" />
              <span>{importing ? "Importing to Database..." : "Commit Import & Update State"}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
